# Generated by Django 4.2.7 on 2023-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('is_veg', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('image', models.CharField(default='https://www.fnasafety.com/wp-content/uploads/2016/04/ComingSoon2-fnasafety.png', max_length=500)),
            ],
        ),
    ]
