# Generated by Django 4.2.7 on 2023-12-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='is_veg',
            new_name='isveg',
        ),
    ]
